# Generated by Django 4.2.22 on 2025-06-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("heure", models.TimeField(default="12:00:00")),
                ("date", models.DateTimeField()),
                ("lieu", models.CharField(max_length=255)),
                ("capacite", models.IntegerField(default=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[("Ouvert", "Ouvert"), ("Complet", "Complet")],
                        max_length=15,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="evenements_images/"
                    ),
                ),
            ],
        ),
    ]
