# Generated by Django 4.2.22 on 2025-07-08 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("evenement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieEvenement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("Concert", "Concert"),
                            ("Conference", "Conference"),
                            ("Croisade", "Croisade"),
                            ("Congres", "Congres"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="evenement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("A venir", "A venir"),
                    ("En cours", "En cours"),
                    ("Termine", "Termine"),
                    ("Annule", "Annule"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="evenement",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evenements",
                to="evenement.categorieevenement",
            ),
        ),
    ]
