# Generated by Django 4.2.22 on 2025-06-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membre",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "mot_de_passe",
                    models.CharField(
                        default="pbkdf2_sha256$600000$dqrNkw0CGz2eItfVKPIVlq$ZYbJiir1pKPN2K0k7eWHhpU9IyRE54dd/qTnDWlbg6I=",
                        max_length=128,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Baptisé", "Baptisé"),
                            ("Non Baptisé", "Non Baptisé"),
                        ],
                        default="Non Baptisé",
                        max_length=15,
                    ),
                ),
                (
                    "approbation",
                    models.CharField(
                        choices=[
                            ("En attente", "En attente"),
                            ("Approuvé", "Approuvé"),
                            ("Rejeté", "Rejeté"),
                        ],
                        default="En attente",
                        max_length=15,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("Homme", "Homme"), ("Femme", "Femme")], max_length=10
                    ),
                ),
                ("adresse", models.TextField()),
                ("date_naissance", models.DateField()),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
