# Generated by Django 4.2.22 on 2025-06-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membre", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$ZHRLLH2ykG4yBePEfmUTeu$serMB3cpsW1yCAUKCXZQV2YRSzlt6ni4r6Xhf/F8GTo=",
                max_length=128,
            ),
        ),
    ]
