# Generated by Django 4.2.22 on 2025-06-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membre", "0002_alter_membre_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$cHLstEfsPGhDw0eZvtXKU0$SrbOl5eaIw74wItVmwLvyMWSc1xiZtXWT6Lw7ltVYx8=",
                max_length=128,
            ),
        ),
    ]
