# Generated by Django 4.2.22 on 2025-06-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membre", "0003_alter_membre_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$9pHytEZF4g28FRFH9bQWtr$Tb5BlY3M5l+cIUbQyTtkeLjxj+UrXwV6G+j5/mD7Sw0=",
                max_length=128,
            ),
        ),
    ]
