# Generated by Django 4.2.22 on 2025-07-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membre", "0004_alter_membre_mot_de_passe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membre",
            name="mot_de_passe",
            field=models.CharField(
                default="pbkdf2_sha256$600000$Tonz8rOnCp03YFDd5hm1wy$KYc0VgXTKEtO97ms93dmdMBumfJJO6Hq4QyA2y7B7bk=",
                max_length=128,
            ),
        ),
    ]
